version: '3.8'

networks:
  kong-net:
    external: true
  application-market-network:
    driver: bridge
  realtime-shopping-network:
    driver: bridge

services:
  application:
    image: 'retefagioli-market-spring:latest'
    build:
      context: ./services/retefagioli-market-backend/src/main/docker/
    container_name: application-market
    depends_on:
      - database
    ports:
      - "60000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-market:5432/retefagioli-market
      - SPRING_DATASOURCE_USERNAME=exsuslabs
      - SPRING_DATASOURCE_PASSWORD=exsuslabs
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - application-market-network
      - kong-net

  database:
    image: 'retefagioli-market-database:latest'
    build:
      context: ./services/retefagioli-market-backend/src/main/docker/postgres/
    container_name: database-market
    environment:
      - POSTGRES_USER=exsuslabs
      - POSTGRES_PASSWORD=exsuslabs
    expose:
      - "5432"
    networks:
      - application-market-network

  kong:
    image: 'market-kong:latest'
    build:
      context: ./services/kong-gateway/
    container_name: market-kong
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: on-failure
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 120s
      timeout: 10s
      retries: 3
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    networks:
      - kong-net
    
  realtime-shopping:
    image: 'realtime-shopping:latest'
    build:
      context: ./services/realtime-shopping/
    container_name: realtime-shopping
    restart: always
    environment:
      - MONGODB_CONFIG_PASSWORD=exsuslabs
      - MONGODB_CONFIG_USERNAME=exsuslabs
      - MONGODB_CONFIG_CONNECTION=mongodb://realtime-database:27017/
    ports:
      - "8080:8080"
    depends_on:
      - realtime-database
    networks:
      - realtime-shopping-network
      - kong-net

  realtime-database:
    image: 'mongo:latest'
    container_name: realtime-database 
    restart: on-failure
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=exsuslabs
      - MONGO_INITDB_ROOT_PASSWORD=exsuslabs
    networks:
      - realtime-shopping-network
