name: Deploy and Test
on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install to Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman
        run: postman login --with-api-key ${{ secrets.API_KEY_POSTMAN }}
      - name: Download Collections and Schemas from Repository
        run: git clone https://github.com/Exsus-Labs/retefagioli-market-api.git
      - name: Run the application
        run: sh ./run.sh
      - name: Run API tests
        run: postman collection run "${{ github.workspace }}/retefagioli-market-api/postman/collections/User Management.json" --integration-id "135861-${{ github.run_id }}"
