version: '3.8'

networks:
  default:
    external:
      name: "kong-net"



services:
  application:
    image: 'retefagioli-market-spring:latest'
    build:
      context: .
    container_name: application-market
    depends_on:
      - database
    ports:
      - "60000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-market:5432/retefagioli-market
      - SPRING_DATASOURCE_USERNAME=exsuslabs
      - SPRING_DATASOURCE_PASSWORD=exsuslabs
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  database:
    image: 'retefagioli-market-database:latest'
    build:
      context: postgres/.
    container_name: database-market
    environment:
      - POSTGRES_USER=exsuslabs
      - POSTGRES_PASSWORD=exsuslabs
    expose:
      - "5432"

  kong-database:
    image: postgres:alpine
    container: kong-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    network:
      - kong-net

  kong-migration:
    image: kong:alpine
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kongpass
    command: kong migrations bootstrap
    restart: on-failure
    network:
      - kong-net
    depends_on:
      - kong-database

    kong:
    image: kong:alpine
    container_name: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: on-failure
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    links:
      - kong-database:kong-database
    depends_on:
      - kong-migrations
