name: Realtime-shopping validation

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
            
      - name: Run cargo check
        working-directory: ./services/realtime-shopping/
        run: cargo check
      
      - uses: Swatinem/rust-cache@v2
      - name: Build Realtime-shopping
        working-directory: ./services/realtime-shopping/
        run: cargo build
      
      - name: Check with cargo fmt
        working-directory: ./services/realtime-shopping/
        run: cargo fmt --all -- --check
      
      - name: Check with clippy
        working-directory: ./services/realtime-shopping/
        run: cargo clippy --all-targets --all-features -- -D warnings
      
      - name: Run unit tests
        run: cargo test -v --tests
